extends Node

const ID = "MudKipster.Webfishing101DoodleExpansion"
onready var Lure = get_node("/root/SulayreLure")

func _ready():
	Lure.add_content(ID,"aero_dwarf_doodlefish","mod://resources/aero_dwarf_doodlefish.tres")
	Lure.add_content(ID,"alhazred_doodlefish","mod://resources/alhazred_doodlefish.tres")
	Lure.add_content(ID,"angler_doodlefish","mod://resources/angler_doodlefish.tres")
	Lure.add_content(ID,"beastman_doodlefish","mod://resources/beastman_doodlefish.tres")
	Lure.add_content(ID,"butterscotch_doodlefish","mod://resources/butterscotch_doodlefish.tres")
	Lure.add_content(ID,"cat_monk_doodlefish","mod://resources/cat_monk_doodlefish.tres")
	Lure.add_content(ID,"crab_doodlefish","mod://resources/crab_doodlefish.tres")
	Lure.add_content(ID,"cyrus_doodlefish","mod://resources/cyrus_doodlefish.tres")
	Lure.add_content(ID,"dalia_doodlefish","mod://resources/dalia_doodlefish.tres")
	Lure.add_content(ID,"deer_knight_doodlefish","mod://resources/deer_knight_doodlefish.tres")
	Lure.add_content(ID,"doodlefish","mod://resources/doodlefish.tres")
	Lure.add_content(ID,"doodlefishette","mod://resources/doodlefishette.tres")
	Lure.add_content(ID,"dworgyn_doodlefish","mod://resources/dworgyn_doodlefish.tres")
	Lure.add_content(ID,"dyvim_whitehart_doodlefish","mod://resources/dyvim_whitehart_doodlefish.tres")
	Lure.add_content(ID,"elik_silverfist_doodlefish","mod://resources/elik_silverfist_doodlefish.tres")
	Lure.add_content(ID,"flytrap_doodlefish","mod://resources/flytrap_doodlefish.tres")
	Lure.add_content(ID,"golden_goose_doodlefish","mod://resources/golden_goose_doodlefish.tres")
	Lure.add_content(ID,"goliath_doodlefish","mod://resources/goliath_doodlefish.tres")
	Lure.add_content(ID,"guard_doodlefish","mod://resources/guard_doodlefish.tres")
	Lure.add_content(ID,"halston_doodlefish","mod://resources/halston_doodlefish.tres")
	Lure.add_content(ID,"kiliman_copperleaf_doodlefish","mod://resources/kiliman_copperleaf_doodlefish.tres")
	Lure.add_content(ID,"lydia_doodlefish","mod://resources/lydia_doodlefish.tres")
	Lure.add_content(ID,"merle_doodlefish","mod://resources/merle_doodlefish.tres")
	Lure.add_content(ID,"moolinda_doodlefish","mod://resources/moolinda_doodlefish.tres")
	Lure.add_content(ID,"morganthe_doodlefish","mod://resources/morganthe_doodlefish.tres")
	Lure.add_content(ID,"mummified_doodlefish","mod://resources/mummified_doodlefish.tres")
	Lure.add_content(ID,"nalia_dunestrider_doodlefish","mod://resources/nalia_dunestrider_doodlefish.tres")
	Lure.add_content(ID,"napoleguin_doodlefish","mod://resources/napoleguin_doodlefish.tres")
	Lure.add_content(ID,"ninja_pig_doodlefish","mod://resources/ninja_pig_doodlefish.tres")
	Lure.add_content(ID,"old_one_doodlefish","mod://resources/old_one_doodlefish.tres")
	Lure.add_content(ID,"pacal_doodlefish","mod://resources/pacal_doodlefish.tres")
	Lure.add_content(ID,"qismah_doodlefish","mod://resources/qismah_doodlefish.tres")
	Lure.add_content(ID,"satyr_doodlefish","mod://resources/satyr_doodlefish.tres")
	Lure.add_content(ID,"steelhead_doodlefish","mod://resources/steelhead_doodlefish.tres")
	Lure.add_content(ID,"tezcat_threestar_doodlefish","mod://resources/tezcat_threestar_doodlefish.tres")
	Lure.add_content(ID,"water_mole_doodlefish","mod://resources/water_mole_doodlefish.tres")
	Lure.add_content(ID,"zander_doodlefish","mod://resources/zander_doodlefish.tres")
	Lure.add_content(ID,"zeus_doodlefish","mod://resources/zeus_doodlefish.tres")
